# Generated by Django 2.2.2 on 2019-06-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='_dateCreated',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='_quizDescription',
            new_name='quizDescription',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='_quizName',
            new_name='quizName',
        ),
    ]
