# Generated by Django 2.2.2 on 2019-06-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20190629_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='_questionText',
            new_name='questionText',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='_quiz',
            new_name='quiz',
        ),
    ]
