# Generated by Django 2.2.2 on 2019-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20190629_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='_correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='_pointValue',
            new_name='pointValue',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='_voters',
            new_name='voters',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='_votes',
            new_name='votes',
        ),
    ]
